name: build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      uses: actions/setup-node@v1
      with:
        node-version: '18'

    - name: Build
      run: |
        npm install --save-exact esbuild
        npm install -D tailwindcss
        make
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
